version: "3.8"
services:
  db-migrate-test:
    image: migrate/migrate:v4.15.2
    volumes:
      - ./src/application/database/migrations:/migrations
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - assis_network

  db-test:
    image: postgres:15
    env_file:
      - .env.example
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${DB_USER} -d $${DB_PASSWORD}'"]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - assis_network
    ports:
      - 5433:5432
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]