CREATE TABLE IF NOT EXISTS accounts (
  id VARCHAR PRIMARY KEY,
  balance BIGINT NOT NULL,
  last_transaction_id VARCHAR,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);